spring:
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      clientId: 686958905155840
      clientSecret: 94a36c31fd23f6cb04eda69c1650dd30
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

logging:
  level:
    org.springframework.security: DEBUG